# Simple Docker Compose for Development
version: '3.8'

services:
  frontend:
    build: ./apps/frontend
    ports:
      - "4200:80"
    depends_on:
      - security-api
      - core-api

  security-api:
    build: ./apps/security
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:password123@mysql:3306/sistema_trazabilidad
    depends_on:
      - mysql

  core-api:
    build: ./apps/core
    ports:
      - "8001:8001"
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://root:password123@mysql:3306/sistema_trazabilidad
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: sistema_trazabilidad
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
