# ===================================
# Configuración Railway - Sistema de Trazabilidad
# Compatible con Windows + WSL2
# Despliega: Backend API + Frontend + Database
# ===================================

[build]
builder = "DOCKERFILE"

# ===================================
# SERVICIO 1: Backend API (Symfony)
# ===================================
[[services]]
name = "trazabilidad-api"
source = "."
dockerfile = "Dockerfile.api"

[services.variables]
APP_ENV = "prod"
SYMFONY_ENV = "prod"
JWT_SECRET_KEY = "config/jwt/private.pem" 
JWT_PUBLIC_KEY = "config/jwt/public.pem"
JWT_PASSPHRASE = "c4906f9c855b52ecc705def9dd62b37baca62e0cbde1e109db968a50c33615dc"
CORS_ALLOW_ORIGIN = "^https://.*\\.railway\\.app$"
TZ = "America/Lima"
# DATABASE_URL se configurará automáticamente con la DB de Railway

[services.healthcheck]
path = "/health"
timeout = 30
interval = 60

# ===================================  
# SERVICIO 2: Frontend (Angular)
# ===================================
[[services]]
name = "trazabilidad-frontend"
source = "."
dockerfile = "Dockerfile.frontend"

[services.variables]
NODE_ENV = "production"
TZ = "America/Lima"

[services.healthcheck]
path = "/health"
timeout = 30
interval = 60

# ===================================
# SERVICIO 3: Base de Datos (MySQL)
# ===================================
[[services]]
name = "trazabilidad-db"
plugin = "mysql"

[services.variables]
MYSQL_DATABASE = "sistema_trazabilidad"
# MYSQL_ROOT_PASSWORD se genera automáticamente por Railway

# ===================================
# CONFIGURACIÓN GLOBAL
# ===================================
[environments.production]
# Todas las variables de entorno globales

[environments.production.variables]
TZ = "America/Lima"
# APP_SECRET se genera automáticamente
