services:
  # Backend API (Symfony)
  - type: web
    name: trazabilidad-api
    env: php
    plan: starter
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: trazabilidad-db
          property: connectionString
      - key: JWT_SECRET_KEY
        value: config/jwt/private.pem
      - key: JWT_PUBLIC_KEY
        value: config/jwt/public.pem
      - key: CORS_ALLOW_ORIGIN
        value: "^https://.*\\.onrender\\.com$"

  # Frontend (Angular)
  - type: web
    name: trazabilidad-frontend
    env: static
    plan: starter
    buildCommand: |
      cd apps/frontend
      npm install
      npm run build
    staticPublishPath: apps/frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: trazabilidad-db
    plan: starter
