# Render configuration file
services:
  # Frontend Angular + Nginx
  - type: web
    name: trazabilidad-frontend
    env: docker
    dockerfilePath: ./apps/frontend/Dockerfile
    plan: free
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production

  # Security API (Symfony)
  - type: web
    name: trazabilidad-security-api
    env: docker
    dockerfilePath: ./apps/security/Dockerfile
    plan: free
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: trazabilidad-db
          property: connectionString
      - key: CORS_ALLOW_ORIGIN
        value: https://trazabilidad-frontend.onrender.com

  # Core API (Symfony)  
  - type: web
    name: trazabilidad-core-api
    env: docker
    dockerfilePath: ./apps/core/Dockerfile
    plan: free
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: trazabilidad-db
          property: connectionString
      - key: CORS_ALLOW_ORIGIN
        value: https://trazabilidad-frontend.onrender.com

# Database
databases:
  - name: trazabilidad-db
    databaseName: sistema_trazabilidad
    user: trazabilidad
    plan: free
