# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    default_filter_set_settings:
        format: webp
    filter_sets:
        mini:
            format: webp
            quality: 50
            filters:
                thumbnail: { size: [ 40, 40 ], mode: outbound }
                background: { color: '#FDFDFD' }
        small:
            format: webp
            quality: 75
            filters:
                thumbnail: { size: [ 150, 150 ], mode: outbound }
                background: { color: '#FFFFFF' }
        large:
            format: webp
            quality: 75
            filters:
                thumbnail: { size: [ 800, 600 ], mode: inset }
                interlace: #Establecer carga progresiva en la imagen
                    mode: line
                background: { color: '#00FFFF' }
        custom:
            format: webp
            quality: 75
