security:
    providers:
        jwt:
            lexik_jwt: ~
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: jwt
            jwt: ~
            logout:
                path: /logout
        main:
            pattern: ^/
        image_resolver:
            pattern: ^/media/cache/resolve
            security: false
    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/*, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Core\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
